### ISSUE TITLE
Annos folder content

### ISSUE THREAD

**Issue by AdePommereau** [FlyingMoon-GitHub/ACNet#4]
Hello,
Thanks for your repo. I have a question regarding the content of the annos folder. You have detailed it as so:

<img width="284" alt="layout" src="https://user-images.githubusercontent.com/60758533/148192791-d441f52b-00b6-4b4a-9dc7-28c9595a929d.png">

But it is not the official layout of the dataset:

<img width="132" alt="image" src="https://user-images.githubusercontent.com/60758533/148193125-940e083a-b607-4e62-a86c-34415e6806cc.png">

What is in the annos_train.txt and annos_test.txt files?

Thank you very much

**Comment by FlyingMoon-GitHub** [comment]
这些文件是根据原始数据集的标签文件生成的，目的在于维持读取过程的统一。我本人生成的标签文件见[附件](https://github.com/FlyingMoon-GitHub/ACNet/files/7816345/dataset.zip)。
These files are generated based on annotation files in original datasets in order to standardize the reading process. The annotation files generated by myself are provided in the [attach file](https://github.com/FlyingMoon-GitHub/ACNet/files/7816345/dataset.zip).

**Comment by FlyingMoon-GitHub** [comment]
这些文件是根据原始数据集的标签文件生成的，目的在于维持读取过程的统一。我已经在[该评论](https://github.com/FlyingMoon-GitHub/ACNet/issues/1#issuecomment-823153400)中说明了其格式。如您需要，我本人生成的标签文件见[附件](https://github.com/FlyingMoon-GitHub/ACNet/files/7816400/data.zip)。
These files are generated based on annotation files in original datasets in order to standardize the reading process. I've shown the format of annotation files in [this comment](https://github.com/FlyingMoon-GitHub/ACNet/issues/1#issuecomment-823153400). For your requirement, the annotation files generated by myself are provided in the [attach file](https://github.com/FlyingMoon-GitHub/ACNet/files/7816400/data.zip).

**Comment by AdePommereau** [comment]
Amazing. Thank you very much!

**Comment by AdePommereau** [comment]
Amazing, Thanks for your help!
